package model.parser.analizadorSintactico;
/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 15;
  /** RegularExpression Id. */
  int CUENTA = 16;
  /** RegularExpression Id. */
  int INDICADOR = 17;
  /** RegularExpression Id. */
  int ID = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "<NUM>",
    "<CUENTA>",
    "<INDICADOR>",
    "<ID>",
  };

}
